apiVersion: v1
kind: ConfigMap
metadata:
  name: nivesh-tree-config
  namespace: nivesh-tree
data:
  NODE_ENV: "production"
  PORT: "5000"
  # MongoDB URI will be set via environment variable or secret
  # MONGODB_URI: "mongodb://mongo:27017/nivesh_tree"
