apiVersion: apps/v1
kind: Deployment
metadata:
  name: nivesh-tree
  namespace: nivesh-tree
  labels:
    app: nivesh-tree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nivesh-tree
  template:
    metadata:
      labels:
        app: nivesh-tree
    spec:
      containers:
      - name: nivesh-tree
        image: vibhanshuthakurdocker/nivesh-tree:latest  # Replace with your actual image name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: api
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nivesh-tree-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nivesh-tree-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nivesh-tree-secrets
              key: JWT_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: nivesh-tree-secrets
              key: MONGODB_URI
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: nivesh-tree-secrets
              key: ENCRYPTION_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
