apiVersion: v1
kind: Secret
metadata:
  name: nivesh-tree-secrets
  namespace: nivesh-tree
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your_value" | base64
  
  # JWT Secret (replace with your actual JWT secret)
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl
  
  # MongoDB URI (replace with your actual MongoDB connection string)
  # Example: mongodb://username:password@mongodb-service:27017/nivesh_tree
  MONGODB_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9uaXZlc2hfdHJlZQ==
  
  # Encryption Key (32 characters long)
  ENCRYPTION_KEY: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl
